"""
Gemini AI Service for Code Analysis and Beginner-Friendly Tutoring.
"""

import os
import json
import re
from typing import Dict, Any, List, Optional
import urllib.request
import urllib.error

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_MODEL = "gemini-3.7-flash"

SYSTEM_ANALYSIS_PROMPT = """You are CodeFix AI, an expert programming tutor designed specifically for beginners and students.
Your goal is to analyze user-submitted code in Python, C, C++, Java, or JavaScript, detect any errors, explain them in simple, friendly, jargon-free English, and provide full corrected code.

CRITICAL INSTRUCTIONS:
1. Tone: Warm, encouraging, patient programming tutor.
2. Simplicity: Avoid confusing academic jargon. Explain concepts using real-world analogies or simple phrasing (e.g. instead of 'TypeError: unsupported operand type', say 'You are trying to combine a number and text. Python cannot add them together without converting the number to text first.').
3. Line numbers: Accurately locate the line where the error or issue occurs (1-indexed). If it is a whole-file or conceptual issue with unknown line, set line to null.
4. Corrected Code: Provide the COMPLETE, functional corrected version of the code, properly indented and ready to run.
5. If NO error is found:
   - set "hasError": false
   - set "errorType": "No Error"
   - set "errorMessage": "No syntax or runtime errors detected."
   - explain what the code does well, and provide 2-3 clean code quality or optimization suggestions.

You MUST reply ONLY with a single valid JSON object adhering strictly to this JSON format:
{
  "hasError": true,
  "errorType": "Syntax Error",
  "line": 5,
  "errorMessage": "Expected ':' after condition",
  "offendingCode": "if x > 10",
  "explanation": "Python requires a colon after an if condition to mark the start of the indented block.",
  "whyItHappened": "The if statement was written without the required colon at the end.",
  "howToFix": "Add ':' at the end of line 5: 'if x > 10:'.",
  "correctedCode": "# Full corrected code here...",
  "suggestions": [
    "Check the syntax of your if statements.",
    "Use consistent 4-space indentation."
  ]
}

Allowed errorType values: "Syntax Error", "Runtime Error", "Logical Error", "Warning", "Code Quality Issue", "Optimization Suggestion", "No Error".
"""

def clean_json_response(raw_text: str) -> str:
    """Strips markdown code fences and whitespace from JSON response."""
    text = raw_text.strip()
    if text.startswith("```"):
        # Remove opening ```json or ```
        text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.IGNORECASE)
        # Remove closing ```
        text = re.sub(r"\s*```$", "", text)
    return text.strip()

def analyze_code_with_gemini(language: str, code: str, static_hints: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Sends code to Gemini API for structured error analysis.
    """
    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        raise ValueError("GEMINI_API_KEY is not configured in the environment.")

    static_context = ""
    if static_hints and static_hints.get("has_syntax_error"):
        static_context = f"\nStatic AST Parser Hint: Detected potential syntax issue on line {static_hints.get('line')}: {static_hints.get('message')}. Offending snippet: '{static_hints.get('offending_line')}'"

    user_prompt = f"""Please analyze the following {language.upper()} code for errors, bugs, or improvements:

```{language}
{code}
```
{static_context}

Provide your beginner-friendly tutor analysis as valid JSON matching the specified structure."""

    payload = {
        "contents": [
            {
                "parts": [
                    {"text": user_prompt}
                ]
            }
        ],
        "systemInstruction": {
            "parts": [
                {"text": SYSTEM_ANALYSIS_PROMPT}
            ]
        },
        "generationConfig": {
            "responseMimeType": "application/json",
            "temperature": 0.2
        }
    }

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent?key={api_key}"
    
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "User-Agent": "aistudio-build"
        },
        method="POST"
    )

    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            candidates = res_data.get("candidates", [])
            if not candidates:
                raise ValueError("No response generated by Gemini.")
            
            raw_text = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
            cleaned = clean_json_response(raw_text)
            parsed_json = json.loads(cleaned)

            # Ensure all required keys exist
            return {
                "hasError": bool(parsed_json.get("hasError", False)),
                "errorType": str(parsed_json.get("errorType", "No Error")),
                "line": parsed_json.get("line"),
                "errorMessage": str(parsed_json.get("errorMessage", "Analysis complete")),
                "offendingCode": str(parsed_json.get("offendingCode", "")),
                "explanation": str(parsed_json.get("explanation", "")),
                "whyItHappened": str(parsed_json.get("whyItHappened", "")),
                "howToFix": str(parsed_json.get("howToFix", "")),
                "correctedCode": str(parsed_json.get("correctedCode", code)),
                "suggestions": list(parsed_json.get("suggestions", []))
            }
    except urllib.error.HTTPError as http_err:
        err_body = http_err.read().decode("utf-8")
        raise RuntimeError(f"Gemini API HTTP {http_err.code}: {err_body}")
    except json.JSONDecodeError as json_err:
        raise ValueError(f"Unable to parse AI response as JSON: {str(json_err)}")

def generate_chat_reply(
    message: str,
    language: str,
    code: str,
    analysis: Optional[Dict[str, Any]] = None,
    history: Optional[List[Dict[str, str]]] = None
) -> str:
    """
    Handles follow-up questions from the user with full code and analysis context.
    """
    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        raise ValueError("GEMINI_API_KEY is not configured in the environment.")

    system_instruction = f"""You are CodeFix AI, a patient and friendly code tutor chatting with a beginner student.
You have the context of the user's active code, the detected error, and the proposed fix in {language.upper()}.
Always be helpful, encouraging, concise, and clear. If they ask to explain line-by-line, walk them through it step-by-step.
If they ask for alternative solutions, show a clean alternative with a short explanation."""

    analysis_summary = ""
    if analysis:
        analysis_summary = f"""
Current Analysis Context:
- Error Type: {analysis.get('errorType')}
- Error Message: {analysis.get('errorMessage')}
- Error Line: {analysis.get('line')}
- Explanation: {analysis.get('explanation')}
- Corrected Code:
{analysis.get('correctedCode')}
"""

    prompt = f"""Current Code ({language.upper()}):
```{language}
{code}
```
{analysis_summary}

User Question: {message}

Please reply in a helpful, conversational, beginner-friendly manner."""

    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "systemInstruction": {"parts": [{"text": system_instruction}]},
        "generationConfig": {"temperature": 0.4}
    }

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent?key={api_key}"
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json", "User-Agent": "aistudio-build"},
        method="POST"
    )

    with urllib.request.urlopen(req, timeout=30) as response:
        res_data = json.loads(response.read().decode("utf-8"))
        candidates = res_data.get("candidates", [])
        if not candidates:
            return "I apologize, but I could not generate a response. Please ask again!"
        return candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
